name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Configurar Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar Dependências
      run: |
        pip install flet
        # Não precisamos instalar requirements.txt se só usarmos o flet aqui

    - name: Restaurar Chave do Firebase
      run: echo '${{ secrets.FIREBASE_JSON }}' > firebase_key.json

    # --- O TRUQUE DE MESTRE COMEÇA AQUI ---
    
    - name: Gerar Chave de Assinatura (Fake Key)
      run: |
        keytool -genkeypair -v \
          -keystore release.keystore \
          -alias mykeyalias \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -storepass password123 \
          -keypass password123 \
          -dname "CN=Fabricio App, OU=IT, O=MyOrg, L=Uberlandia, S=MG, C=BR"

    - name: Construir APK (Release Assinado)
      # Agora passamos a chave para o Flet. Ele vai achar que é um build oficial!
      run: |
        yes | flet build apk --verbose \
          --android-signing-key-store release.keystore \
          --android-signing-key-store-password password123 \
          --android-signing-key-alias mykeyalias \
          --android-signing-key-password password123

    - name: Upload do APK
      uses: actions/upload-artifact@v4
      with:
        name: agenda-app-release
        path: build/apk/build/app/outputs/flutter-apk/app-release.apk
