name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Configurar Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar Flet
      run: pip install flet

    - name: Restaurar Chave do Firebase
      run: echo '${{ secrets.FIREBASE_JSON }}' > firebase_key.json

    # --- PASSO 1: Forçar Aceite de Licenças (Funcionou!) ---
    - name: Forçar Aceite de Licenças
      run: |
        mkdir -p "$ANDROID_HOME/licenses"
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
        yes | flutter doctor --android-licenses || true

    # --- PASSO 2: Gerar Keystore (Usando caminho absoluto) ---
    - name: Gerar Keystore
      run: |
        # $(pwd) pega o caminho completo da pasta atual
        keytool -genkeypair -v \
          -keystore $(pwd)/release.keystore \
          -alias mykeyalias \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -storepass password123 \
          -keypass password123 \
          -dname "CN=Fabricio, OU=IT, O=MyOrg, L=Uberlandia, S=MG, C=BR"

    # --- PASSO 3: Construir APK (Passando o endereço completo da chave) ---
    - name: Construir APK
      run: |
        # Salva o caminho absoluto numa variável
        KEY_PATH=$(pwd)/release.keystore
        echo "Usando chave em: $KEY_PATH"
        
        yes | flet build apk --verbose \
          --android-signing-key-store "$KEY_PATH" \
          --android-signing-key-store-password password123 \
          --android-signing-key-alias mykeyalias \
          --android-signing-key-password password123
          - name: Upload do APK
      uses: actions/upload-artifact@v4
      with:
        name: agenda-app-release
        path: "**/*.apk"

